# Generated by Django 5.1.2 on 2024-12-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('brand', models.CharField(max_length=150, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Бренд')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('transmission', models.CharField(max_length=50, verbose_name='Трасмиссия')),
                ('engine_volume', models.CharField(max_length=50, verbose_name='Мощность двигателя')),
                ('drive', models.CharField(max_length=50, verbose_name='Привод')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('power_volume', models.CharField(max_length=5, verbose_name='Мощность')),
                ('brand_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand')),
            ],
        ),
    ]
