# Generated by Django 5.1.2 on 2024-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
